SELECT
    PRODUCT_ID ,
    UPPER(TRIM(PRODUCT_CATEGORY_NAME)) AS PRODUCT_CATEGORY_NAME,
    PRODUCT_NAME_LENGTH,
    PRODUCT_DESCRIPTION_LENGTH,
    PRODUCT_PHOTOS_QTY,
    PRODUCT_WEIGHT_G,
    PRODUCT_LENGTH_CM ,
    PRODUCT_HEIGHT_CM,
    PRODUCT_WIDTH_CM 
FROM {{ source('bronze','PRODUCTS')}}
