{{ config(
    materialized='table'
) }}

SELECT

    dc.CUSTOMER_KEY,
    dc.CUSTOMER_ID,
    dc.CUSTOMER_CITY,
    dc.CUSTOMER_STATE,

    COUNT(DISTINCT fs.ORDER_ID) AS TOTAL_ORDERS,

COUNT(DISTINCT fs.PRODUCT_KEY) AS TOTAL_PRODUCTS,

COALESCE(ROUND(SUM(fs.TOTAL_ITEM_AMOUNT),2),0) AS TOTAL_SPENT,

COALESCE(ROUND(AVG(fs.TOTAL_ITEM_AMOUNT),2),0) AS AVG_ORDER_VALUE,

MIN(fs.ORDER_PURCHASE_TIMESTAMP) AS FIRST_PURCHASE_DATE,

MAX(fs.ORDER_PURCHASE_TIMESTAMP) AS LAST_PURCHASE_DATE,

COALESCE(ROUND(AVG(fs.DELIVERY_DAYS),2),0) AS AVG_DELIVERY_DAYS,

COALESCE(
    SUM(
        CASE
            WHEN fs.LATE_DELIVERY THEN 1
            ELSE 0
        END
    ),
    0
) AS LATE_DELIVERIES,
 CASE

    WHEN COALESCE(SUM(fs.TOTAL_ITEM_AMOUNT),0) >= 5000 THEN 'PLATINUM'
    WHEN COALESCE(SUM(fs.TOTAL_ITEM_AMOUNT),0) >= 2000 THEN 'GOLD'
    WHEN COALESCE(SUM(fs.TOTAL_ITEM_AMOUNT),0) >= 1000 THEN 'SILVER'
    ELSE 'BRONZE'

END AS CUSTOMER_SEGMENT 

FROM {{ ref('dim_customers') }} dc

LEFT JOIN {{ ref('fact_sales') }} fs

ON dc.CUSTOMER_KEY = fs.CUSTOMER_KEY

GROUP BY

    dc.CUSTOMER_KEY,
    dc.CUSTOMER_ID,
    dc.CUSTOMER_CITY,
    dc.CUSTOMER_STATE