{{ config(
    materialized='table'
) }}

SELECT

    dp.PRODUCT_KEY,
    dp.PRODUCT_ID,
    dp.PRODUCT_CATEGORY_NAME,

    COUNT(DISTINCT fs.ORDER_ID) AS TOTAL_ORDERS,

    COUNT(*) AS TOTAL_ITEMS_SOLD,

    ROUND(SUM(fs.TOTAL_ITEM_AMOUNT),2) AS TOTAL_REVENUE,

    ROUND(AVG(fs.PRICE),2) AS AVG_PRODUCT_PRICE,

    ROUND(AVG(fs.FREIGHT_VALUE),2) AS AVG_FREIGHT_COST,

    ROUND(AVG(fs.DELIVERY_DAYS),2) AS AVG_DELIVERY_DAYS,

    MAX(fs.ORDER_PURCHASE_TIMESTAMP) AS LAST_PURCHASE_DATE

FROM {{ ref('dim_products') }} dp

LEFT JOIN {{ ref('fact_sales') }} fs

ON dp.PRODUCT_KEY = fs.PRODUCT_KEY

GROUP BY

    dp.PRODUCT_KEY,
    dp.PRODUCT_ID,
    dp.PRODUCT_CATEGORY_NAME