{{ config(materialized='table') }}

SELECT

    DATE_KEY,

    PURCHASE_YEAR,
    PURCHASE_MONTH,

    COUNT(DISTINCT ORDER_ID)            AS TOTAL_ORDERS,

    COUNT(DISTINCT CUSTOMER_KEY)        AS TOTAL_CUSTOMERS,

    COUNT(DISTINCT PRODUCT_KEY)         AS TOTAL_PRODUCTS,

    SUM(TOTAL_ITEM_AMOUNT)              AS TOTAL_REVENUE,

    SUM(FREIGHT_VALUE)                  AS TOTAL_FREIGHT,

    AVG(TOTAL_ITEM_AMOUNT)              AS AVG_ORDER_VALUE,

    AVG(DELIVERY_DAYS)                  AS AVG_DELIVERY_DAYS,

    SUM(CASE WHEN LATE_DELIVERY THEN 1 ELSE 0 END)
        AS LATE_DELIVERIES

FROM {{ ref('fact_sales') }}

GROUP BY

    DATE_KEY,
    PURCHASE_YEAR,
    PURCHASE_MONTH