{{ config(
    materialized='table'
) }}

SELECT DISTINCT

    CAST(ORDER_PURCHASE_TIMESTAMP AS DATE) AS DATE_KEY,

    YEAR(ORDER_PURCHASE_TIMESTAMP) AS YEAR,

    MONTH(ORDER_PURCHASE_TIMESTAMP) AS MONTH,

    DAY(ORDER_PURCHASE_TIMESTAMP) AS DAY,

    MONTHNAME(ORDER_PURCHASE_TIMESTAMP) AS MONTH_NAME,

    DAYNAME(ORDER_PURCHASE_TIMESTAMP) AS DAY_NAME,

    QUARTER(ORDER_PURCHASE_TIMESTAMP) AS QUARTER

FROM {{ ref('stg_orders') }}

WHERE ORDER_PURCHASE_TIMESTAMP IS NOT NULL