CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

  CREATE DATABASE IF NOT EXISTS PORTFOLIO_DB;

  CREATE SCHEMA IF NOT EXISTS PORTFOLIO_DB.RAW;

  ALTER SCHEMA IF EXISTS PORTFOLIO_DB.RAW RENAME TO BRONZE;
  
  CREATE SCHEMA IF NOT EXISTS PORTFOLIO_DB.STAGING;

 ALTER SCHEMA IF EXISTS PORTFOLIO_DB.STAGING RENAME TO SILVER;
  CREATE SCHEMA IF NOT EXISTS PORTFOLIO_DB.MART;

ALTER SCHEMA IF EXISTS PORTFOLIO_DB.MART RENAME TO PORTFOLIO_DB.GOLD;


  SELECT CURRENT_ACCOUNT(), CURRENT_REGION();

  SELECT CURRENT_ORGANIZATION_NAME(), CURRENT_ACCOUNT_NAME();

  