USE DATABASE PORTFOLIO_DB;
USE SCHEMA BRONZE;

-- Record counts
SELECT 'CUSTOMERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CUSTOMERS
UNION ALL
SELECT 'ORDERS', COUNT(*) FROM ORDERS
UNION ALL
SELECT 'ORDER_ITEMS', COUNT(*) FROM ORDER_ITEMS
UNION ALL
SELECT 'PRODUCTS', COUNT(*) FROM PRODUCTS
UNION ALL
SELECT 'SELLERS', COUNT(*) FROM SELLERS
UNION ALL
SELECT 'ORDER_PAYMENTS', COUNT(*) FROM ORDER_PAYMENTS;


SELECT * FROM PORTFOLIO_DB.BRONZE.CUSTOMERS LIMIT 5;


SELECT * FROM PORTFOLIO_DB.BRONZE.ORDERS LIMIT 5;
SELECT * FROM PORTFOLIO_DB.BRONZE.ORDER_PAYMENTS LIMIT 5;
SELECT * FROM PORTFOLIO_DB.BRONZE.ORDER_ITEMS LIMIT 5;
SELECT * FROM PORTFOLIO_DB.BRONZE.PRODUCTS LIMIT 5;
SELECT * FROM PORTFOLIO_DB.BRONZE.SELLERS LIMIT 5;